Repository ridsuteri/Awesome-Chrome-Extensions, pull requests merged in 2022-03, with the labels that each got.

#6 created Programing_meme chrome extension
  programing_Meme/logo.png
  programing_Meme/manifest.json
  programing_Meme/popup.html
  programing_Meme/script.js
Labels: GSSoC'22, Level-3

#40 added issue forms
  .github/ISSUE_TEMPLATE/Bug_report.yaml
  .github/ISSUE_TEMPLATE/Feature_request.yaml
Labels: GSSoC22, Level-2

#39 docs: Add PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GSSoC22, Level-2

#44 Minor enhancements in README.md
  README.md
Labels: GSSoC22, Level-1

#34 Water-Break
  water-break/icon128.png
  water-break/icon16.png
  water-break/icon48.png
  water-break/index.css
  water-break/index.html
  water-break/index.js
  water-break/manifest.json
  water-break/sound1.mp3
Labels: GSSoC22, Level-2

#51 feat(dark-mode): Add dark mode chrome extension
  Dark-Mode/Readme.md
  Dark-Mode/buttonOff.js
  Dark-Mode/buttonOn.js
  Dark-Mode/icons/dark-mode-128.png
  Dark-Mode/icons/dark-mode-16.png
  Dark-Mode/icons/dark-mode-32.png
  Dark-Mode/icons/dark-mode-48.png
  Dark-Mode/icons/dark-mode-64.png
  Dark-Mode/img/img_dark.jpeg
  Dark-Mode/img/img_white.jpeg
  Dark-Mode/manifest.json
  Dark-Mode/popup.html
  Dark-Mode/popup.js
  Dark-Mode/style/popup.css
Labels: GSSoC22, Level-2

#15 i add new extension BMI EXTENSIONS
  BMI Calculator/Logo-code.png
  BMI Calculator/manifest.json
  BMI Calculator/popup.html
  BMI Calculator/script.js
  BMI Calculator/style.css
Labels: GSSoC22, Level-2

#59 Add Url-Shortener
  URL-shortener/README.md
  URL-shortener/logo.png
  URL-shortener/logo16.png
  URL-shortener/logo48.png
  URL-shortener/manifest.json
  URL-shortener/option.js
  URL-shortener/options.html
  URL-shortener/popup.html
  URL-shortener/popup.js
  URL-shortener/spectre.min.css
Labels: GSSoC22, Level-2

#61 docs: Added (docs) Issue template
  .github/ISSUE_TEMPLATE/doc_issue.yaml
Labels: GSSoC22, Level-2

#60 To-Do List Extension added
  To-Do Extension/content.js
  To-Do Extension/icon.png
  To-Do Extension/manifest.json
  To-Do Extension/popup.html
  To-Do Extension/style.css
Labels: GSSoC22, Level-2

#72 Currency Calculator Extension Added #41
  currency-calc-extension/background.js
  currency-calc-extension/images/money-exchange.png
  currency-calc-extension/images/transfer.png
  currency-calc-extension/manifest.json
  currency-calc-extension/popup.css
  currency-calc-extension/popup.html
  currency-calc-extension/popup.js
Labels: GSSoC22, Level-2

#66 Dynamic calender
  Calender 2/index.html
  Calender 2/manifest.json
  Calender 2/script.js
  Calender 2/style.css
  QR-Generator/README.md
  QR-Generator/manifest.json
  QR-Generator/popup.html
  QR-Generator/qr.png
  QR-Generator/script.js
  QR-Generator/style.css
Labels: GSSoC22, Level-2

#73 Parential control chrome extension
  Parential/README.md
  Parential/background.js
  Parential/images/get_started128.png
  Parential/images/get_started16.png
  Parential/images/get_started32.png
  Parential/images/get_started48.png
  Parential/manifest.json
  Parential/popup.html
  Parential/popup.js
  Parential/style/index.css
Labels: GSSoC22, Level-3

#82 Added Pomodoro timer
  Pomodoro_Timer/icon.png
  Pomodoro_Timer/manifest.json
  Pomodoro_Timer/popup.html
  Pomodoro_Timer/readme.md
  Pomodoro_Timer/script.js
  Pomodoro_Timer/styles.css
Labels: GSSoC22, Level-2

#84 Added QR-Generator Extension
  QR-Generator/README.md
  QR-Generator/manifest.json
  QR-Generator/popup.html
  QR-Generator/qr.png
  QR-Generator/script.js
  QR-Generator/style.css
Labels: GSSoC22, Level-2

#86 Added a Weather app extension
  Weather app/README.md
  Weather app/images/day/clear.jpg
  Weather app/images/day/cloudy.jpg
  Weather app/images/day/rainy.jpg
  Weather app/images/day/snowy.jpg
  Weather app/images/icon.png
  Weather app/images/night/clear.jpg
  Weather app/images/night/cloudy.jpg
  Weather app/images/night/rainy.jpg
  Weather app/images/night/snowy.jpg
  Weather app/js/index.js
  Weather app/manifest.json
  Weather app/popup.html
  Weather app/styles/style.css
Labels: GSSoC22, Level-2

#95 Adding Countdown-Timer
  Countdown-timer./README.md
  Countdown-timer./app.js
  Countdown-timer./index.html
  Countdown-timer./manifest.json
  Countdown-timer./style.css
Labels: GSSoC22, Level-2

#99 Update README.md
  README.md
Labels: documentation

#101 Khush
  Poor-Jokes/popup.html
  Poor-Jokes/script.js
  Poor-Jokes/style.css
Labels: GSSoC22, Level-1

#102 Adding maths addition game
  Maths_addition/README.md
  Maths_addition/app.js
  Maths_addition/index.html
  Maths_addition/manifest.json
  Maths_addition/style.css
Labels: GSSoC22, Level-2

#103 AUTO REFRESHER
  Auto Refresher/background.js
  Auto Refresher/images/example-go.png
  Auto Refresher/images/example-stop.png
  Auto Refresher/images/go-hover.png
  Auto Refresher/images/go.png
  Auto Refresher/images/refresh-icon.png
  Auto Refresher/images/refresh-icon128.png
  Auto Refresher/images/refresh-icon16.png
  Auto Refresher/images/refresh-icon48.png
  Auto Refresher/images/stop-hover.png
  Auto Refresher/images/stop.png
  Auto Refresher/manifest.json
  Auto Refresher/popup.html
  Auto Refresher/popup.js
  Auto Refresher/readme.md
  Auto Refresher/styles.css
Labels: GSSoC22, Level-2

#107 added changes
  BMI Calculator/BMI Extention Working Images/BMINormal.png
  BMI Calculator/BMI Extention Working Images/BMIOverweight.png
  BMI Calculator/BMI Extention Working Images/BMIUnderweight.png
  BMI Calculator/BMI Extention Working Images/BMIextention.png
  Calender 2/Dynamic Calender images/Dynamic Calender1.png
  Calender 2/Dynamic Calender images/Dynamic Calender2.png
  Code Launcher/images/Code Aider image.png
Labels: GSSoC22, Level-2

#108 Competitive Trainer 1.0
  Competitive Trainer/.gitignore
  Competitive Trainer/css/codechef.css
  Competitive Trainer/css/codeforces.css
  Competitive Trainer/css/leetcode.css
  Competitive Trainer/css/main.css
  Competitive Trainer/html/codechef.html
  Competitive Trainer/html/codeforces.html
  Competitive Trainer/html/leetcode.html
  Competitive Trainer/js/background.js
  Competitive Trainer/js/codechef.js
  Competitive Trainer/js/codeforces.js
  Competitive Trainer/js/jquery.js
  Competitive Trainer/js/leetcode.js
  Competitive Trainer/js/main.js
  Competitive Trainer/logos/codechef.png
  Competitive Trainer/logos/codeforces.png
  Competitive Trainer/logos/leetcode.png
  Competitive Trainer/logos/loader.gif
  Competitive Trainer/manifest.json
Labels: GSSoC22, Level-3

#111 Images added to Folders
  Maths_addition/README.md
  Maths_addition/images/math.jpg
  Maths_addition/images/math2.jpg
  Parential/images/workingimages.jpg
  Pomodoro_Timer/images/workingimage.png
  Poor-Jokes/images/workingimages.png
  QR-Generator/images/workingimages.png
Labels: GSSoC22, Level-2

#105 Adding CountDown Timer
  Countdown-timer/README.md
  Countdown-timer/app.js
  Countdown-timer/index.html
  Countdown-timer/manifest.json
  Countdown-timer/style.css
Labels: GSSoC22, Level-2

#112 Link saver
  links-tabs-saver/icon.png
  links-tabs-saver/index.html
  links-tabs-saver/index.js
  links-tabs-saver/manifest.json
  links-tabs-saver/style.css
Labels: GSSoC22, Level-2

#114 Images and Readme added
  To-Do Extension/images/workingimage.png
  URL-shortener/README.md
  URL-shortener/images/workingimage.png
  currency-calc-extension/images/workingimage1.png
  currency-calc-extension/images/workingimage2.png
  links-tabs-saver/images/workingimage.png
  programing_Meme/images/workingimage.png
Labels: GSSoC22, Level-2

#121 Stop Watch Extension
  Stop Watch/README.md
  Stop Watch/clock2.png
  Stop Watch/manifest.json
  Stop Watch/popup.html
  Stop Watch/script.js
  Stop Watch/style.css
Labels: GSSoC22, Level-2

#122 List The Bookmarks
  List The Bookmarks/README.md
  List The Bookmarks/icon.png
  List The Bookmarks/manifest.json
  List The Bookmarks/popup.css
  List The Bookmarks/popup.html
  List The Bookmarks/popup.js
  Stop Watch/README.md
Labels: GSSoC22, Level-2

#127 Github Extension Implemented
  Github Extension/images/img0.JPG
  Github Extension/images/img1.JPG
  Github Extension/images/img2.JPG
  Github Extension/images/img3.JPG
  Github Extension/logo.png
  Github Extension/manifest.json
  Github Extension/popup.html
  Github Extension/script.js
  Github Extension/style.css
Labels: GSSoC22, Level-2

#130 Added CSS Background Generator Extension
  CSS Background Generator/README.md
  CSS Background Generator/index.css
  CSS Background Generator/index.html
  CSS Background Generator/index.js
  CSS Background Generator/manifest.json
  CSS Background Generator/pic.png
Labels: GSSoC22, Level-2

#133 Revert 3 motivation unlimited
  Motivation_unlimited/logo.png
  Motivation_unlimited/manifest.json
  Motivation_unlimited/popup.html
  Motivation_unlimited/script.js
  Motivation_unlimited/style.css
Labels: GSSoC22, Level-2

#135 Adding Coin Toss game
  Coin toss/app.js
  Coin toss/heads.png
  Coin toss/index.html
  Coin toss/manifest.json
  Coin toss/style.css
  Coin toss/tails.png
Labels: GSSoC22, Level-2

#136 GRE Vocab : These Extension help the GRE aspirants get all vocab Word + Definition
  grevocab/.env.production
  grevocab/.gitignore
  grevocab/README.md
  grevocab/build/asset-manifest.json
  grevocab/build/index.html
  grevocab/build/logo.png
  grevocab/build/manifest.json
  grevocab/build/robots.txt
  grevocab/build/static/css/main.2a935c19.css
  grevocab/build/static/css/main.2a935c19.css.map
  grevocab/build/static/js/787.1d3fe108.chunk.js
  grevocab/build/static/js/787.1d3fe108.chunk.js.map
  grevocab/build/static/js/main.cde22c7c.js
  grevocab/build/static/js/main.cde22c7c.js.LICENSE.txt
  grevocab/build/static/js/main.cde22c7c.js.map
  grevocab/package-lock.json
  grevocab/package.json
  grevocab/public/index.html
  grevocab/public/logo.png
  grevocab/public/manifest.json
  grevocab/public/robots.txt
  grevocab/src/App.css
  grevocab/src/App.js
  grevocab/src/App.test.js
  grevocab/src/GREVocabList.js
  grevocab/src/ScreenShots/GREVocabDemo.mp4
  grevocab/src/ScreenShots/GREVocabImg.PNG
  grevocab/src/favicon (1).ico
  grevocab/src/index.css
  grevocab/src/index.js
  grevocab/src/reportWebVitals.js
  grevocab/src/setupTests.js
  grevocab/yarn.lock
Labels: GSSoC22, Level-2

#137 Awesome Chrome Extension Website
  Awesome Chrome Extensions Website/index.html
  Awesome Chrome Extensions Website/nav.js
  Awesome Chrome Extensions Website/navstyle.css
  Awesome Chrome Extensions Website/script.js
  Awesome Chrome Extensions Website/style.css
Labels: GSSoC22, Level-3

#139 Enhanced README file
  README.md
Labels: GSSoC22, Level-1
