Repository ridsuteri/Awesome-Chrome-Extensions, pull requests merged in 2022-04, with the labels that each got.

#142 IT Calculator
  IT_Income_Tax_Calculator/calculate.js
  IT_Income_Tax_Calculator/icon.jpeg
  IT_Income_Tax_Calculator/it.html
  IT_Income_Tax_Calculator/manifest.json
Labels: GSSoC22, Level2

#145 Added time zone finder extension
  Time Zone Finder/Readme.md
  Time Zone Finder/index.html
  Time Zone Finder/manifest.json
  Time Zone Finder/script.js
Labels: GSSoC22, Level2

#152 Added ad blocker extension
  Ad Blocker/Images/Ad logo.png
  Ad Blocker/Readme.md
  Ad Blocker/manifest.json
  Ad Blocker/script.js
Labels: GSSoC22, Level2

#154 RGB to HEX convertor added
  rgb to hex convertor/ReadMe.md
  rgb to hex convertor/icon.png
  rgb to hex convertor/image/1.png
  rgb to hex convertor/image/2.png
  rgb to hex convertor/image/a.jpg
  rgb to hex convertor/image/b.png
  rgb to hex convertor/image/c.png
  rgb to hex convertor/img.png
  rgb to hex convertor/manifest.json
  rgb to hex convertor/popup.html
  rgb to hex convertor/script.js
  rgb to hex convertor/style.css
  script.js
Labels: GSSoC22, Level2

#157 Bugsolve of Manifest V2
  Poor-Jokes/manifest.json
Labels: GSSoC22, Level1

#155 Adding Weight Conversion
  Weight conversion tool/README.md
  Weight conversion tool/app.js
  Weight conversion tool/index.html
  Weight conversion tool/manifest.json
  Weight conversion tool/styles.css
Labels: GSSoC22, Level2

#161 News Extension Added
  News Extension/images/img0.JPG
  News Extension/logo.png
  News Extension/manifest.json
  News Extension/popup.html
  News Extension/script.js
  News Extension/style.css
Labels: GSSoC22, Level2

#162 Pinterest extension for Chrome browser - A save button for saving your ideas from pinterest website
  Pinterest_extension/.vscode/settings.json
  Pinterest_extension/board.html
  Pinterest_extension/images/icon-128x128.png
  Pinterest_extension/images/icon-16x16.png
  Pinterest_extension/images/icon-32x32.png
  Pinterest_extension/images/icon-48x48.png
  Pinterest_extension/images/pinterest-mock/add.png
  Pinterest_extension/images/pinterest-mock/ellipse.png
  Pinterest_extension/images/pinterest-mock/send.png
  Pinterest_extension/images/pinterest-mock/up-arrow.png
  Pinterest_extension/images/pinterest-mock/upper-right-arrow.png
  Pinterest_extension/manifest.json
  Pinterest_extension/options.html
  Pinterest_extension/popup.html
  Pinterest_extension/readme.md
  Pinterest_extension/scripts/background.js
  Pinterest_extension/scripts/pinterest-mock/board.js
  Pinterest_extension/scripts/popup_script.js
  Pinterest_extension/styles/pinterest-mock/board.css
  Pinterest_extension/styles/pinterest-mock/modal_styles.css
  Pinterest_extension/styles/pinterest-mock/normalize.css
  Pinterest_extension/styles/pinterest-mock/pin_styles.css
  Pinterest_extension/styles/popup_styles.css
Labels: GSSoC22, Level2

#170 Add Country capital extension
  Country_Capital_Extension/bg.jpg
  Country_Capital_Extension/logo.png
  Country_Capital_Extension/manifest.json
  Country_Capital_Extension/popup.html
  Country_Capital_Extension/script.js
  Country_Capital_Extension/style.css
Labels: GSSoC22, Level2

#166 Adding Height conversion tool
  Height Conversion tool/app.js
  Height Conversion tool/index.html
  Height Conversion tool/manifest.json
  Height Conversion tool/style.css
Labels: GSSoC22, Level2

#164 News Extension Enhancement added
  News Extension/images/img0.JPG
  News Extension/images/img1.JPG
  News Extension/images/img2.JPG
  News Extension/popup.html
  News Extension/script.js
  News Extension/style.css
Labels: GSSoC22, Level2

#174 adding loan calculator
  Loan calculator/app.js
  Loan calculator/index.html
  Loan calculator/manifest.json
  Loan calculator/style.css
Labels: GSSoC22, Level2

#181 Binary To Decimal Converter And Vice-Versa
  Binary_To_Decimal_converter/manifest.json
  Binary_To_Decimal_converter/popup.html
  Binary_To_Decimal_converter/script.js
  Binary_To_Decimal_converter/style.css
Labels: GSSoC22, Level2

#173 Toxicity Classification Extension added
  Toxicity Classification Extension/images/img0.JPG
  Toxicity Classification Extension/img1.JPG
  Toxicity Classification Extension/logo.png
  Toxicity Classification Extension/manifest.json
  Toxicity Classification Extension/popup.html
  Toxicity Classification Extension/script.js
  Toxicity Classification Extension/style.css
Labels: GSSoC22, Level2

#185 NotePad Extension
  Note Pad/README.md
  Note Pad/img/1.1.png
  Note Pad/img/2.2.png
  Note Pad/img/256px-Icon-notepad.svg.png
  Note Pad/manifest.json
  Note Pad/popup.html
  Note Pad/script.js
Labels: GSSoC22, Level2

#182 Quick Access Google
  Quick Access Google/README.md
  Quick Access Google/img/Apps-Google-Chrome-App-List-icon.png
  Quick Access Google/img/Screenshot 2022-04-12 071532.png
  Quick Access Google/manifest.json
  Quick Access Google/popup.html
  Quick Access Google/script.js
Labels: GSSoC22, Level2

#186 Images Added
  Ad Blocker/AdBlocker image.png
  Binary_To_Decimal_converter/binarytodecimal.mp4
  CSS Background Generator/CSS Background Image.png
  Coin toss/Coin Toss Images.png
  Competitive Trainer/Competitive Trainer Image.png
  Countdown-timer/CountDown Timer  Image.png
  Country_Capital_Extension/Country Capital gif.mp4
  Height Conversion tool/Height Conversion Tool Image.png
  IT_Income_Tax_Calculator/IT IncomeTax cal Image.png
  Links-Launcher/Links Launcher Image.png
  List The Bookmarks/List the Bookmarks Images.png
  Loan calculator/Loan Cal Image.png
  Motivation_unlimited/Motivation Unlimited Image.png
  Pinterest_extension/Pinterest Image.jpg
  Stop Watch/Stop Watch Image.png
  TIC-TAC-TOE/TICTACTOE Image.png
  Time Zone Finder/TimeZone Finder Image.png
  Weather app/Weather app Image.png
  Weight conversion tool/Weight Convertor Image.png
  calculator/Calculator Image.png
  style.css
Labels: GSSoC22, Level2

#183 Company Insider Extension Added
  Company Insider/images/img0.JPG
  Company Insider/images/img1.JPG
  Company Insider/images/img2.JPG
  Company Insider/logo.png
  Company Insider/manifest.json
  Company Insider/popup.html
  Company Insider/script.js
  Company Insider/styles.css
Labels: GSSoC22, Level2

#189 Books Recommendation Extension
  Books_Recommendation/book.jpg
  Books_Recommendation/book3.png
  Books_Recommendation/manifest.json
  Books_Recommendation/popup.html
  Books_Recommendation/script.js
  Books_Recommendation/style.css
Labels: GSSoC22, Level2

#184 Adding user taking form
  User taking form/README.md
  User taking form/index.html
  User taking form/manifest.json
  User taking form/script.js
  User taking form/style.css
  User taking form/submit.html
Labels: GSSoC22, Level3

#192 Background Remover added
  Background Remover/images/img0.JPG
  Background Remover/images/img1.JPG
  Background Remover/logo.png
  Background Remover/manifest.json
  Background Remover/popup.html
  Background Remover/script.js
  Background Remover/styles.css
Labels: GSSoC22, Level2

#198 Twitter context Menus extension
  Twitter Context Menu/README.md
  Twitter Context Menu/event.js
  Twitter Context Menu/img/aok.png
  Twitter Context Menu/img/aok2.png
  Twitter Context Menu/img/logo-twitter-png-5859.png
  Twitter Context Menu/manifest.json
Labels: GSSoC22, Level2

#200 Calculate Age Chrome Extension:
  Calculate Age/index.html
  Calculate Age/logo.png
  Calculate Age/manifest.json
  Calculate Age/readme.md
  Calculate Age/script.js
  Calculate Age/style.css
Labels: GSSoC22, Level2

#201 Adding auto right extension
  Auto Right/README.md
  Auto Right/index.html
  Auto Right/manifest.json
  Auto Right/script.js
  Auto Right/style.css
Labels: GSSoC22, Level2

#206 Food calorie extension
  Food_Calorie_Extension/bg.jpg
  Food_Calorie_Extension/logo.png
  Food_Calorie_Extension/manifest.json
  Food_Calorie_Extension/popup.html
  Food_Calorie_Extension/script.js
  Food_Calorie_Extension/style.css
Labels: GSSoC22, Level2

#209 Control chrome tabs
  Control Chrome Tabs/README.md
  Control Chrome Tabs/event.js
  Control Chrome Tabs/img/000001.png
  Control Chrome Tabs/img/000002.png
  Control Chrome Tabs/img/chrome_logo_PNG33.png
  Control Chrome Tabs/manifest.json
Labels: GSSoC22, Level2

#213 Vat calculator
  VAT_Calculator/icon.png
  VAT_Calculator/images/ui.jpg
  VAT_Calculator/images/workingImage.jpg
  VAT_Calculator/manifest.json
  VAT_Calculator/popup.html
  VAT_Calculator/readme.md
  VAT_Calculator/script.js
  VAT_Calculator/styles.css
Labels: GSSoC22, Level2

#214 Movie recommendation extension
  Movies_Recommendation/manifest.json
  Movies_Recommendation/movie.jpg
  Movies_Recommendation/movies.png
  Movies_Recommendation/popup.html
  Movies_Recommendation/script.js
  Movies_Recommendation/style.css
Labels: GSSoC22, Level2

#220 Background Remover Enhancement added
  Background Remover/images/img2.JPG
  Background Remover/popup.html
  Background Remover/script.js
  Background Remover/styles.css
Labels: GSSoC22, Level2
