Repository ridsuteri/Awesome-Chrome-Extensions, pull requests merged in 2022-05, with the labels that each got.

#217 Improve notepad
  Note Pad/README.md
  Note Pad/img/1.1.png
  Note Pad/img/2.2.png
  Note Pad/img/Screenshot 2022-04-22 113100.png
  Note Pad/popup.html
  Note Pad/script.js
Labels: GSSoC22, Level2

#222 Phone Checker added
  Phone Checker/images/img0.JPG
  Phone Checker/images/img1.JPG
  Phone Checker/logo.png
  Phone Checker/manifest.json
  Phone Checker/popup.html
  Phone Checker/script.js
  Phone Checker/styles.css
Labels: GSSoC22, Level2

#227 Added all the extensions to Website
  Github Extension/images/img4.jpg
  index.html
  navstyle.css
  script.js
  style.css
Labels: GSSoC22, Level2

#230 Translator
  Translator/README.md
  Translator/img/Screenshot 2022-04-29 222446.png
  Translator/img/add-readme (1).png
  Translator/img/kindpng_6026265.png
  Translator/index.html
  Translator/manifest.json
  Translator/myscript.js
Labels: GSSoC22, Level2

#231 Recipe Extension added
  Recipe Extension/images/img0.JPG
  Recipe Extension/logo.png
  Recipe Extension/manifest.json
  Recipe Extension/popup.html
  Recipe Extension/script.js
  Recipe Extension/styles.css
Labels: GSSoC22, Level2

#235 Riddle Extension
  Riddle_Extension/bg.png
  Riddle_Extension/manifest.json
  Riddle_Extension/popup.html
  Riddle_Extension/script.js
  Riddle_Extension/style.css
Labels: GSSoC22, Level2

#241 GK quiz extension
  GK_Quiz/bg.png
  GK_Quiz/manifest.json
  GK_Quiz/popup.html
  GK_Quiz/script.js
  GK_Quiz/style.css
Labels: GSSoC22, Level2

#243 Call app
  Smartphone Call/1.jpg
  Smartphone Call/index.html
  Smartphone Call/logo.png
  Smartphone Call/manifest.json
  Smartphone Call/preview1.gif
  Smartphone Call/preview2.jpg
  Smartphone Call/readme.md
  Smartphone Call/script.js
  Smartphone Call/script1.js
  Smartphone Call/script2.js
  Smartphone Call/style.css
Labels: GSSoC22, Level2

#245 Guess Cartoon
  Guess_Cartoon/images/1.png
  Guess_Cartoon/images/10.png
  Guess_Cartoon/images/2.png
  Guess_Cartoon/images/3.jpg
  Guess_Cartoon/images/4.png
  Guess_Cartoon/images/5.png
  Guess_Cartoon/images/6.png
  Guess_Cartoon/images/7.png
  Guess_Cartoon/images/8.png
  Guess_Cartoon/images/9.png
  Guess_Cartoon/manifest.json
  Guess_Cartoon/popup.html
  Guess_Cartoon/script.js
  Guess_Cartoon/style.css
Labels: GSSoC22, Level2

#251 Window Remover
  Window_Remover/README.md
  Window_Remover/img/add-readme (1).png
  Window_Remover/img/toppng.com-web-browser-computer-icons-vector-web-page-download-web-browser-clipart-695x630.png
  Window_Remover/img/winR.png
  Window_Remover/manifest.json
  Window_Remover/myscript.js
  Window_Remover/popup.html
Labels: GSSoC22, Level2

#260 Text To Speech
  Text To Speech/index.html
  Text To Speech/logo.png
  Text To Speech/manifest.json
  Text To Speech/preview1.jpg
  Text To Speech/script.js
  Text To Speech/script2.js
  Text To Speech/style.css
  Text To Speech/style2.css
Labels: GSSoC22, Level2

#265 Speech Recognition
  Speech Recognition/README.md
  Speech Recognition/img/kisspng-speech-recognition-human-voice-technology-plain-te-5af8480eab18d6.6293122015262208147008.png
  Speech Recognition/img/ss1speech.png
  Speech Recognition/img/ss2speech.png
  Speech Recognition/index.html
  Speech Recognition/manifest.json
  Speech Recognition/myscript1.js
  Speech Recognition/myscript2.js
  Speech Recognition/popup.html
Labels: GSSoC22

#262 Facts Extension
  Facts_Extension/bg.jpg
  Facts_Extension/manifest.json
  Facts_Extension/popup.html
  Facts_Extension/script.js
  Facts_Extension/style.css
Labels: GSSoC22

#273 Vocabulary extension
  Vocabulary Extension/bg.jpg
  Vocabulary Extension/manifest.json
  Vocabulary Extension/popup.html
  Vocabulary Extension/script.js
  Vocabulary Extension/style.css
Labels: GSSoC22, Level2

#271 MarkDown
  Markdown Preview/index.html
  Markdown Preview/logo.png
  Markdown Preview/manifest.json
  Markdown Preview/script.js
  Markdown Preview/script1.js
  Markdown Preview/script2.js
  Markdown Preview/script3.js
  Markdown Preview/style.css
  Markdown Preview/style1.css
Labels: GSSoC22, Level2

#272 Auto Fill
  Auto Fill/content.js
  Auto Fill/index.html
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-grid.css
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-grid.css.map
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-grid.min.css
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-grid.min.css.map
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-grid.rtl.css
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-grid.rtl.css.map
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-grid.rtl.min.css
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-grid.rtl.min.css.map
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-reboot.css
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-reboot.css.map
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-reboot.min.css
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-reboot.min.css.map
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-reboot.rtl.css
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-reboot.rtl.css.map
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-reboot.rtl.min.css
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-reboot.rtl.min.css.map
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-utilities.css
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-utilities.css.map
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-utilities.min.css
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-utilities.min.css.map
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-utilities.rtl.css
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-utilities.rtl.css.map
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-utilities.rtl.min.css
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap-utilities.rtl.min.css.map
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap.css
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap.css.map
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap.min.css
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap.min.css.map
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap.rtl.css
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap.rtl.css.map
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap.rtl.min.css
  Auto Fill/libs/bootstrap-5.1.1-dist/css/bootstrap.rtl.min.css.map
  Auto Fill/libs/bootstrap-5.1.1-dist/js/bootstrap.bundle.js
  Auto Fill/libs/bootstrap-5.1.1-dist/js/bootstrap.bundle.js.map
  Auto Fill/libs/bootstrap-5.1.1-dist/js/bootstrap.bundle.min.js
  Auto Fill/libs/bootstrap-5.1.1-dist/js/bootstrap.bundle.min.js.map
  Auto Fill/libs/bootstrap-5.1.1-dist/js/bootstrap.esm.js
  Auto Fill/libs/bootstrap-5.1.1-dist/js/bootstrap.esm.js.map
  Auto Fill/libs/bootstrap-5.1.1-dist/js/bootstrap.esm.min.js
  Auto Fill/libs/bootstrap-5.1.1-dist/js/bootstrap.esm.min.js.map
  Auto Fill/libs/bootstrap-5.1.1-dist/js/bootstrap.js
  Auto Fill/libs/bootstrap-5.1.1-dist/js/bootstrap.js.map
  Auto Fill/libs/bootstrap-5.1.1-dist/js/bootstrap.min.js
  Auto Fill/libs/bootstrap-5.1.1-dist/js/bootstrap.min.js.map
  Auto Fill/manifest.json
  Auto Fill/script.js
Labels: GSSoC22, Level2

#270 Wiki Search
  Wiki Search/background.js
  Wiki Search/images/icon128.png
  Wiki Search/images/icon16.png
  Wiki Search/images/icon32.png
  Wiki Search/images/icon48.png
  Wiki Search/manifest.json
  Wiki Search/readme.md
Labels: GSSoC22, Level2

#269 Pick the Color Extension🎨
  Color Picker/index.html
  Color Picker/manifest.json
  Color Picker/readme.md
  Color Picker/script.js
  Color Picker/style.css
Labels: GSSoC22, Level1

#281 File counter
  File counter/README.md
  File counter/background.js
  File counter/img/pngkit_evaluation-png_2045314.png
  File counter/img/ssfilecount.png
  File counter/manifest.json
  File counter/myscript.js
  File counter/popup.html
Labels: GSSoC22, Level2

#286 Decimal_Hexadecimal_Converter
  Decimal_Hexadecimal_Converter/manifest.json
  Decimal_Hexadecimal_Converter/popup.html
  Decimal_Hexadecimal_Converter/script.js
  Decimal_Hexadecimal_Converter/style.css
Labels: GSSoC22, Level2

#274 Added Analog Clock
  Analog_Clock/2.png
  Analog_Clock/clock.png
  Analog_Clock/index.html
  Analog_Clock/index.js
  Analog_Clock/manifest.json
  Analog_Clock/style.css
Labels: GSSoC22, Level2

#290 Anime Generator
  Random Anime Generator/anime.png.png
  Random Anime Generator/index.html
  Random Anime Generator/logo.png
  Random Anime Generator/manifest.json
  Random Anime Generator/preview.jpg
  Random Anime Generator/script.js
  Random Anime Generator/style.css
Labels: GSSoC22, Level2

#292 Cube Game
  Cube Game/index.html
  Cube Game/logo.png
  Cube Game/manifest.json
  Cube Game/script.js
  Cube Game/script1.js
  Cube Game/style.css
Labels: GSSoC22, Level2

#294 Guess emoji
  Guess_Emoji/images/1.jpg
  Guess_Emoji/images/10.jpg
  Guess_Emoji/images/2.jpg
  Guess_Emoji/images/3.jpg
  Guess_Emoji/images/4.jpg
  Guess_Emoji/images/5.jpg
  Guess_Emoji/images/6.jpg
  Guess_Emoji/images/7.jpg
  Guess_Emoji/images/8.jpg
  Guess_Emoji/images/9.jpg
  Guess_Emoji/manifest.json
  Guess_Emoji/popup.html
  Guess_Emoji/script.js
  Guess_Emoji/style.css
Labels: GSSoC22, Level2

#289 Website changes made
  Auto Fill/autofill image.png
  Auto Right/Auto right image.png
  Color Picker/color picker image.png
  Decimal_Hexadecimal_Converter/Decimal Hexadecimal Convertor image.png
  Github Extension/images/img4.jpg
  Guess_Cartoon/Guess cartoon image.png
  Markdown Preview/markdown preview image.png
  User taking form/User Taking Form image.png
  Wiki Search/wiki search image.png
  index.html
  nav.js
  navstyle.css
  script.js
  style.css
Labels: GSSoC22, Level3

#305 Fahrenheit celsius converter
  Fahrenheit_Celsius_Converter/manifest.json
  Fahrenheit_Celsius_Converter/popup.html
  Fahrenheit_Celsius_Converter/script.js
  Fahrenheit_Celsius_Converter/style.css
Labels: GSSoC22, Level2

#308 Added Cheatsheet Template
  Cheatsheet_Template/copy.png
  Cheatsheet_Template/index.html
  Cheatsheet_Template/manifest.json
  Cheatsheet_Template/prism (1).css
  Cheatsheet_Template/prism (1).js
  Cheatsheet_Template/style.css
Labels: GSSoC22, Level2

#307 Added Moving Car Animation
  Moving_Car/background.jpg
  Moving_Car/car_body.png
  Moving_Car/car_wheel_left.png
  Moving_Car/car_wheel_right.png
  Moving_Car/index.html
  Moving_Car/index.js
  Moving_Car/manifest.json
  Moving_Car/mycar.png
  Moving_Car/sound.mp3
  Moving_Car/style.css
  Moving_Car/track.png
  Moving_Car/trees.png
Labels: GSSoC22, Level2

#301 Blacklist website
  Blacklist Website/background.js
  Blacklist Website/images/icon-128x128.png
  Blacklist Website/images/icon-16x16.png
  Blacklist Website/images/icon-48x48-off.png
  Blacklist Website/images/icon-48x48.png
  Blacklist Website/manifest.json
  Blacklist Website/popup.css
  Blacklist Website/popup.html
  Blacklist Website/popup.js
Labels: GSSoC22, Level2

#278 Added Digital Clock
  digital_clock/2.png
  digital_clock/clock.jpg
  digital_clock/index.html
  digital_clock/manifest.json
  digital_clock/script.js
  digital_clock/style.css
Labels: GSSoC22, Level2

#306 Download Links added
  index.html
  script.js
  style.css
Labels: GSSoC22, Level3

#326 Added Tip Calculator
  Tip Calculator/bg.webp
  Tip Calculator/images.png
  Tip Calculator/index.html
  Tip Calculator/index.js
  Tip Calculator/manifest.json
  Tip Calculator/style.css
Labels: GSSoC22, Level2

#321 Dictionary Chrome Extension added
  Crypto-Currency/logo.png
  Crypto-Currency/manifest.json
  Crypto-Currency/popup.html
  Crypto-Currency/preview.png
  Crypto-Currency/script.js
  Crypto-Currency/style.css
  Dictionary/loading.svg
  Dictionary/logo.png
  Dictionary/manifest.json
  Dictionary/popup.html
  Dictionary/script.js
  Dictionary/styles.css
  Github-File_Structure/background.js
  Github-File_Structure/content.css
  Github-File_Structure/content.js
  Github-File_Structure/fonts/anonymous-pro.woff2
  Github-File_Structure/fonts/devopicons.woff2
  Github-File_Structure/fonts/file-icons.woff2
  Github-File_Structure/fonts/fira-code.woff2
  Github-File_Structure/fonts/fontawesome.woff2
  Github-File_Structure/fonts/inconsolata.woff2
  Github-File_Structure/fonts/iosevka-regular.woff2
  Github-File_Structure/fonts/jetbrains-mono.woff2
  Github-File_Structure/fonts/mfixx.woff2
  Github-File_Structure/fonts/octicons.woff2
  Github-File_Structure/fonts/octotree.woff2
  Github-File_Structure/fonts/recursive-mono.woff2
  Github-File_Structure/fonts/source-code-pro.woff2
  Github-File_Structure/fonts/space-mono.woff2
  Github-File_Structure/fonts/ubuntu-mono.woff2
  Github-File_Structure/icons/icon1024.png
  Github-File_Structure/icons/icon128.png
  Github-File_Structure/icons/icon16.png
  Github-File_Structure/icons/icon19.png
  Github-File_Structure/icons/icon256.png
  Github-File_Structure/icons/icon32.png
  Github-File_Structure/icons/icon38.png
  Github-File_Structure/icons/icon48.png
  Github-File_Structure/icons/icon512.png
  Github-File_Structure/icons/icon64.png
  Github-File_Structure/icons/logo.svg
  Github-File_Structure/images/32px.png
  Github-File_Structure/images/40px.png
  Github-File_Structure/images/throbber.gif
  Github-File_Structure/manifest.json
  Sports_Tracker/index.html
  Sports_Tracker/logo.png
  Sports_Tracker/manifest.json
  Sports_Tracker/script.js
  Sports_Tracker/styles.css
Labels: GSSoC22, Level2

#291 Added Library Website
  Library_Website/index.html
  Library_Website/index.js
  Library_Website/manifest.json
  Library_Website/nn.png
  Library_Website/style.css
Labels: GSSoC22, Level2

#329 Dictionary extension
  Dictionary_Extension/manifest.json
  Dictionary_Extension/popup.html
  Dictionary_Extension/script.js
  Dictionary_Extension/style.css
Labels: GSSoC22, Level2

#344 Adding Emoji-rating
  Emoji-rating/index.html
  Emoji-rating/index.js
  Emoji-rating/manifest.json
  Emoji-rating/style.css
Labels: GSSoC22, Level2

#343 Adding Profile-statistic
  Profile-statistics/index.html
  Profile-statistics/index.js
  Profile-statistics/manifest.json
  Profile-statistics/style.css
Labels: GSSoC22, Level2

#365 DevQuery Comment Generator Implemented
  DevQuery Comment/logo.png
  DevQuery Comment/manifest.json
  DevQuery Comment/popup.html
  DevQuery Comment/script.js
  DevQuery Comment/styles.css
Labels: GSSoC22, Level2

#369 Voice Selected Text Chrome Extension
  Voice Selection/SpeakSel128.png
  Voice Selection/SpeakSel16.png
  Voice Selection/SpeakSel19-active.png
  Voice Selection/SpeakSel19.png
  Voice Selection/SpeakSel256.png
  Voice Selection/SpeakSel48.png
  Voice Selection/background.js
  Voice Selection/content_script.js
  Voice Selection/keycodes.js
  Voice Selection/manifest.json
  Voice Selection/options.html
  Voice Selection/options.js
  Voice Selection/tabs.js
Labels: GSSoC22, Level2

#341 word typing
  Word Typing Game/index.html
  Word Typing Game/logo.png
  Word Typing Game/manifest.json
  Word Typing Game/script.js
  Word Typing Game/style.css
Labels: GSSoC22, Level2

#358 Added Spotify Clone Website
  Spotify_Clone/bg.jpg
  Spotify_Clone/covers/1.jpg
  Spotify_Clone/covers/10.jpg
  Spotify_Clone/covers/2.jpg
  Spotify_Clone/covers/3.jpg
  Spotify_Clone/covers/4.jpg
  Spotify_Clone/covers/5.jpg
  Spotify_Clone/covers/6.jpg
  Spotify_Clone/covers/7.jpg
  Spotify_Clone/covers/8.jpg
  Spotify_Clone/covers/9.jpg
  Spotify_Clone/fontawesome.js
  Spotify_Clone/index.html
  Spotify_Clone/index.js
  Spotify_Clone/logo.png
  Spotify_Clone/manifest.json
  Spotify_Clone/playing.gif
  Spotify_Clone/songs/1.mp3
  Spotify_Clone/songs/2.mp3
  Spotify_Clone/songs/3.mp3
  Spotify_Clone/songs/4.mp3
  Spotify_Clone/songs/5.mp3
  Spotify_Clone/songs/6.mp3
  Spotify_Clone/songs/7.mp3
  Spotify_Clone/songs/8.mp3
  Spotify_Clone/style.css
Labels: GSSoC22, Level2

#382 YouTube Playlist Duration
  Youtube Playlist Duration/background.js
  Youtube Playlist Duration/logo.png
  Youtube Playlist Duration/manifest.json
  Youtube Playlist Duration/script.js
Labels: GSSoC22, Level2

#334 Added Sketchify Chrome Extension
  Sketchify/background-wrapper.js
  Sketchify/background.js
  Sketchify/content_script.js
  Sketchify/devtools.html
  Sketchify/devtools.js
  Sketchify/icon128.png
  Sketchify/icon16.png
  Sketchify/icon48.png
  Sketchify/manifest.json
  Sketchify/popup.css
  Sketchify/popup.html
  Sketchify/popup.js
Labels: GSSoC22, Level2

#384 Country currency extension
  Country_Currency/bg.jpg
  Country_Currency/country_curr.json
  Country_Currency/manifest.json
  Country_Currency/popup.html
  Country_Currency/script.js
  Country_Currency/style.css
Labels: GSSoC22, Level2

#346 Paragraphgenerator
  Paragrph Generator/index.html
  Paragrph Generator/logo.png
  Paragrph Generator/main.js
  Paragrph Generator/manifest.json
  Paragrph Generator/styles.css
Labels: GSSoC22, Level2

#340 Added Extension for Developers
  developer-color/devLogo.png
  developer-color/manifest.json
  developer-color/script.js
  developer-color/style.css
Labels: GSSoC22, Level2

#381 Youtube Skip Ad Chrome Extension
  Youtube Skip Ad/Makefile
  Youtube Skip Ad/manifest.json
  Youtube Skip Ad/skipad.js
Labels: GSSoC22, Level2

#377 Today in History - Chrome Extension Implemented
  Today in History/assets/css/styles.css
  Today in History/assets/images/birth.png
  Today in History/assets/images/event.png
  Today in History/assets/images/hist.jpeg
  Today in History/assets/images/hist.jpg
  Today in History/assets/images/icon.jpeg
  Today in History/assets/images/rip.png
  Today in History/assets/js/script.js
  Today in History/birth.html
  Today in History/death.html
  Today in History/event.html
  Today in History/icon.jpeg
  Today in History/index.html
  Today in History/manifest.json
Labels: GSSoC22, Level2

#378 profile generate
  Profile Generator/index.html
  Profile Generator/logo.png
  Profile Generator/manifest.json
  Profile Generator/readme.md
  Profile Generator/script.js
  Profile Generator/script1.js
  Profile Generator/style.css
Labels: GSSoC22, Level2

#387 Roots extension
  Roots_Quadratic_Eqn/manifest.json
  Roots_Quadratic_Eqn/popup.html
  Roots_Quadratic_Eqn/script.js
  Roots_Quadratic_Eqn/style.css
Labels: GSSoC22, Level2

#363 Implemented Chrome Extension for Dyslexic People
  Dyslexic Help/_locales/ar/messages.json
  Dyslexic Help/_locales/bg/messages.json
  Dyslexic Help/_locales/bn/messages.json
  Dyslexic Help/_locales/ca/messages.json
  Dyslexic Help/_locales/cs/messages.json
  Dyslexic Help/_locales/de/messages.json
  Dyslexic Help/_locales/el/messages.json
  Dyslexic Help/_locales/en/messages.json
  Dyslexic Help/_locales/es/messages.json
  Dyslexic Help/_locales/et/messages.json
  Dyslexic Help/_locales/fa/messages.json
  Dyslexic Help/_locales/fil/messages.json
  Dyslexic Help/_locales/fr/messages.json
  Dyslexic Help/_locales/gu/messages.json
  Dyslexic Help/_locales/hr/messages.json
  Dyslexic Help/_locales/hu/messages.json
  Dyslexic Help/_locales/id/messages.json
  Dyslexic Help/_locales/it/messages.json
  Dyslexic Help/_locales/ja/messages.json
  Dyslexic Help/_locales/kn/messages.json
  Dyslexic Help/_locales/ko/messages.json
  Dyslexic Help/_locales/lv/messages.json
  Dyslexic Help/_locales/ml/messages.json
  Dyslexic Help/_locales/mr/messages.json
  Dyslexic Help/_locales/ms/messages.json
  Dyslexic Help/_locales/nl/messages.json
  Dyslexic Help/_locales/no/messages.json
  Dyslexic Help/_locales/sl/messages.json
  Dyslexic Help/_locales/sr/messages.json
  Dyslexic Help/_locales/sv/messages.json
  Dyslexic Help/_locales/te/messages.json
  Dyslexic Help/_locales/th/messages.json
  Dyslexic Help/_locales/tr/messages.json
  Dyslexic Help/_locales/uk/messages.json
  Dyslexic Help/_locales/vi/messages.json
  Dyslexic Help/_metadata/verified_contents.json
  Dyslexic Help/fonts/opendyslexic/OpenDyslexic-Bold.otf
  Dyslexic Help/fonts/opendyslexic/OpenDyslexic-BoldItalic.otf
  Dyslexic Help/fonts/opendyslexic/OpenDyslexic-Italic.otf
  Dyslexic Help/fonts/opendyslexic/OpenDyslexic-Regular.otf
  Dyslexic Help/fonts/opendyslexic/OpenDyslexicMono-Regular.otf
  Dyslexic Help/images/icons/icon-128.png
  Dyslexic Help/images/icons/icon-48.png
  Dyslexic Help/images/readme.png
  Dyslexic Help/index.html
  Dyslexic Help/manifest.json
  Dyslexic Help/scripts/content.js
  Dyslexic Help/scripts/popup.js
  Dyslexic Help/styles/core/opendyslexic-bold.css
  Dyslexic Help/styles/core/opendyslexic-italic.css
  Dyslexic Help/styles/core/opendyslexic-regular.css
Labels: GSSoC22, Level2

#392 Country language extension
  Country_Lang_Extension/bg.jpg
  Country_Lang_Extension/logo.png
  Country_Lang_Extension/manifest.json
  Country_Lang_Extension/popup.html
  Country_Lang_Extension/script.js
  Country_Lang_Extension/style.css
Labels: GSSoC22, Level2

#394 Background Generator
  Background Generator/index.html
  Background Generator/logo.png
  Background Generator/manifest.json
  Background Generator/readme.md
  Background Generator/script.js
  Background Generator/script2.js
  Background Generator/style.css
Labels: GSSoC22, Level2

#396 adding step-progress-bar
  step-progress-bar/index.html
  step-progress-bar/index.js
  step-progress-bar/manifest.json
  step-progress-bar/style.css
Labels: GSSoC22, Level2

#400 YouTube Save
  Youtube Save/css/editPlaylist.css
  Youtube Save/css/popup.css
  Youtube Save/editPlaylist.html
  Youtube Save/js/background.js
  Youtube Save/js/editPlaylist.js
  Youtube Save/js/jquery.min.js
  Youtube Save/js/playNextVid.js
  Youtube Save/js/popup.js
  Youtube Save/logo.png
  Youtube Save/manifest.json
  Youtube Save/popup.html
Labels: GSSoC22, Level2

#402 Json
  JSON File Formatter/background.js
  JSON File Formatter/content.js
  JSON File Formatter/logo128.png
  JSON File Formatter/logo32.png
  JSON File Formatter/manifest.json
  JSON File Formatter/readme.md
Labels: GSSoC22, Level2

#375 Google Docs Viewer List - Chrome Extension
  GDocs Viewer/background.html
  GDocs Viewer/chrome_ex_oauth.html
  GDocs Viewer/chrome_ex_oauth.js
  GDocs Viewer/chrome_ex_oauthsimple.js
  GDocs Viewer/img/docs_spreadsheets-128.gif
  GDocs Viewer/img/docs_spreadsheets-32.gif
  GDocs Viewer/img/docs_spreadsheets-48.gif
  GDocs Viewer/img/icons/audio.gif
  GDocs Viewer/img/icons/document.gif
  GDocs Viewer/img/icons/file.gif
  GDocs Viewer/img/icons/folder.gif
  GDocs Viewer/img/icons/form.gif
  GDocs Viewer/img/icons/pdf.gif
  GDocs Viewer/img/icons/presentation.gif
  GDocs Viewer/img/icons/spreadsheet.gif
  GDocs Viewer/js/jquery-1.4.1.min.js
  GDocs Viewer/manifest.json
  GDocs Viewer/options.html
  GDocs Viewer/popup.html
Labels: GSSoC22, Level2

#405 DIY extension
  DIY_extension/images/1.jpg
  DIY_extension/images/10.jpg
  DIY_extension/images/2.jpg
  DIY_extension/images/3.jpg
  DIY_extension/images/4.jpg
  DIY_extension/images/5.jpg
  DIY_extension/images/6.jpg
  DIY_extension/images/7.jpg
  DIY_extension/images/8.jpg
  DIY_extension/images/9.jpg
  DIY_extension/manifest.json
  DIY_extension/popup.html
  DIY_extension/script.js
  DIY_extension/style.css
Labels: GSSoC22, Level2

#408 Water To Drink Extension
  WaterToDrink/cover.png
  WaterToDrink/logo.png
  WaterToDrink/manifest.json
  WaterToDrink/popup.html
  WaterToDrink/script.js
  WaterToDrink/style.css
Labels: GSSoC22, Level2

#419 Country code extension
  Country_Code/bg.jpg
  Country_Code/logo.png
  Country_Code/manifest.json
  Country_Code/popup.html
  Country_Code/script.js
  Country_Code/style.css
Labels: GSSoC22, Level2

#422 Guess movie extension
  Guess_Movie/bg.jpg
  Guess_Movie/manifest.json
  Guess_Movie/popup.html
  Guess_Movie/script.js
  Guess_Movie/style.css
Labels: GSSoC22, Level2

#355 Covid color changer
  covid color changer/bermuda-663.png
  covid color changer/index.html
  covid color changer/manifest.json
  covid color changer/readme.md
  covid color changer/script.js
  covid color changer/styles.css
  step-progress-bar/index.html
  step-progress-bar/index.js
  step-progress-bar/manifest.json
  step-progress-bar/style.css
Labels: GSSoC22, Level2

#423 Website Updated
  navstyle.css
  script.js
Labels: GSSoC22, Level3

#426 Daily Horoscope Teller
  Daily Horoscope/bg.jpg
  Daily Horoscope/logo.png
  Daily Horoscope/manifest.json
  Daily Horoscope/popup.html
  Daily Horoscope/popup2.html
  Daily Horoscope/readme.md
  Daily Horoscope/script.js
  Daily Horoscope/script2.js
Labels: GSSoC22, Level2

#427 keycode
  KeyCodes/Index.html
  KeyCodes/manifest.json
  KeyCodes/script.js
  KeyCodes/style.css
Labels: GSSoC22, Level2

#416 Added GitHub Repository Size Extension
  GitHub-Repository-Size/icons/ghrs128.png
  GitHub-Repository-Size/icons/ghrs16.png
  GitHub-Repository-Size/icons/ghrs48.png
  GitHub-Repository-Size/manifest.json
  GitHub-Repository-Size/src/background.js
  GitHub-Repository-Size/src/inject.js
Labels: GSSoC22, Level2

#425 Places Extension
  Places Extension/bg.jpg
  Places Extension/logo.png
  Places Extension/manifest.json
  Places Extension/popup.html
  Places Extension/script.js
  Places Extension/style.css
Labels: GSSoC22, Level2

#424 Date Counter
  Date Counter/index.html
  Date Counter/logo.png
  Date Counter/manifest.json
  Date Counter/readme.md
  Date Counter/script.js
  Date Counter/style.css
Labels: GSSoC22, Level2

#429 Mobile code extension
  Mobile_Code/bg.png
  Mobile_Code/manifest.json
  Mobile_Code/popup.html
  Mobile_Code/script.js
  Mobile_Code/style.css
Labels: GSSoC22, Level2

#435 File Size Viewer
  File Size Viewer and Downloader Github/background.js
  File Size Viewer and Downloader Github/inject.js
  File Size Viewer and Downloader Github/logo.png
  File Size Viewer and Downloader Github/manifest.json
  File Size Viewer and Downloader Github/popup.html
  File Size Viewer and Downloader Github/readme.md
  File Size Viewer and Downloader Github/script.js
Labels: GSSoC22, Level2

#390 Adding Realtime-character-counter
  Realtime-character-counter/index.html
  Realtime-character-counter/index.js
  Realtime-character-counter/manifest.json
  Realtime-character-counter/style.css
Labels: GSSoC22, Level2

#437 Country by capital extension
  Country_Extension/bg.jpg
  Country_Extension/logo.png
  Country_Extension/manifest.json
  Country_Extension/popup.html
  Country_Extension/script.js
  Country_Extension/style.css
Labels: GSSoC22, Level2

#442 Password Strength Background
  PasswordStrengthBackground/PasswordStrengthBackground.css
  PasswordStrengthBackground/PasswordStrengthBackground.js
  PasswordStrengthBackground/manifest.json
  PasswordStrengthBackground/popup.html
Labels: GSSoC22, Level2

#445 hoverboard
  Hoverboard/manifest.json
  Hoverboard/popup.html
  Hoverboard/script.js
  Hoverboard/style.css
Labels: GSSoC22, Level2

#440 Code Github
  Code Github/background.js
  Code Github/logo.png
  Code Github/main.js
  Code Github/manifest.json
  Code Github/style.css
Labels: GSSoC22, Level2

#438 Redirect Link
  Redirect Link Checker/data/grab.js
  Redirect Link Checker/data/inject.js
  Redirect Link Checker/data/logo.png
  Redirect Link Checker/data/popup/index.css
  Redirect Link Checker/data/popup/index.html
  Redirect Link Checker/data/popup/index.js
  Redirect Link Checker/data/popup/tld.js
  Redirect Link Checker/manifest.json
  Redirect Link Checker/worker.js
Labels: GSSoC22, Level2

#446 Country location extension
  Country_Location/bg.jpg
  Country_Location/logo.png
  Country_Location/manifest.json
  Country_Location/popup.html
  Country_Location/script.js
  Country_Location/style.css
Labels: GSSoC22, Level2

#441 Theme Github
  Change Theme Github/app/app.bundle.js
  Change Theme Github/app/app.css
  Change Theme Github/app/background.bundle.js
  Change Theme Github/app/background.js
  Change Theme Github/app/browser-polyfill.js
  Change Theme Github/app/browser-polyfill.js.map
  Change Theme Github/app/bulma.css
  Change Theme Github/app/bulma.css.map
  Change Theme Github/app/content_script.js
  Change Theme Github/app/popup.html
  Change Theme Github/app/popup.js
  Change Theme Github/app/theme.js
  Change Theme Github/app/vendor.js
  Change Theme Github/logo.png
  Change Theme Github/manifest.json
  Change Theme Github/readme.md
Labels: GSSoC22, Level2

#447 Country flag
  Country_Flag/bg.jpg
  Country_Flag/logo.png
  Country_Flag/manifest.json
  Country_Flag/popup.html
  Country_Flag/script.js
  Country_Flag/style.css
Labels: GSSoC22, Level2
